name: Deploy website

on:
  push:
    branches:
      - master
    paths:
      - .github/workflows/deploy-website.yml
      - public/**

jobs:
  publish-website:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      #
      # Upload files to public web server via rsync
      #
      - name: Upload web site
        uses: easingthemes/ssh-deploy@v2.1.1
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-rlgoDzvO"
          SOURCE: "./public/"
          REMOTE_HOST: ${{ secrets.SSH_REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.SSH_REMOTE_USER }}
          TARGET: ${{ secrets.SSH_REMOTE_TARGET }}
